### ISSUE TITLE
User input resharping

### ISSUE THREAD

**Issue by LeGonidec** [NablaT/angular2gen#1]
The names for the inputs should be different at each occurence.Otherwise, the store:true will display the same value each time. For now, only "name" is used. So if you enter "Angular2App" for the name of the application, for example, the generator will suggest you to enter "Angular2App" to state if you want Sass or not.
The user input should also be dealt with in the "prompting" section of the run loop, and not at the default level.
You could also consider saving the configuration in the "configuring" section instead of using store:true, which would make it even cleaner.

**Comment by NablaT** [comment]
Hello LeGonidec, 

Thank you for your contribution. I fixed the issue with the previous input which appears in following inputs. I will get an eye on the configuration section. 

Thank you ;)
