### ISSUE TITLE
Would you like to use Sass? Fails

### ISSUE THREAD

**Issue by Ztarbox** [NablaT/angular2gen#3]
Installation will fail if set to 'y' or 'yes', because 'src/shared/styles/**main.scss**' doesn't exist. Should be 'src/shared/styles/**_main.scss**'.
`this.copy('src/shared/styles/main.scss', 'src/shared/styles/main.scss');`
[Source](https://github.com/NablaT/angular2gen/blob/master/app/index.js#L172)

**Comment by NablaT** [comment]
Hi Ztarbox, thanks for your contribution, I fixed the issue.
