### ISSUE TITLE
Update to angular2rc

### ISSUE THREAD

**Issue by frouyer193** [NablaT/angular2gen#5]
Hey guys, 

Could you update the generator to angular2-rc ? 

Thanks.

**Comment by NablaT** [comment]
Hey frouyer, 

Sure ! We are currently working on this update. We are updating the tasks and we will start the update for the generated project. 

Thank you for your contribution.

**Comment by NablaT** [comment]
Hey frouyer, 

Angular2gen has been updated to angular2-rc in the release 1.0.0 ;)
